[default]
address = "0.0.0.0"
port = 8081
secret_key = "WuNALsM2E+xy7OMXn16LQK6K7DdpJjObJz9wmoSp56Q="

[default.tls]
certs = "certs/cert.pem"
key = "certs/key.pem"

[default.app]
session_duration = "96h"

[default.app.database]
host = "http://localhost:5984"
username = "invex"
password = "invex"
